// eslint.config.cjs
const json = require('@eslint/json').default;
const storybook = require('eslint-plugin-storybook');
const stylisticPlugin = require('@stylistic/eslint-plugin-js');
const jsdoc = require('eslint-plugin-jsdoc');

module.exports = [
  {
    plugins: {
      stylisticPlugin,
      storybook,
      jsdoc,
      json,
    },
  },
  {
    ignores: ['dist/**', 'docs/**', 'storybook-static/**'],
  },
  {
    //storybook

    files: ['**/stories.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
      },
    },
    rules: {
      'storybook/import/no-anonymous-default-export': "off",
      'storybook/await-interactions': "error",
      'storybook/context-in-play-function': "error",
      'storybook/default-exports': "error",
      'storybook/hierarchy-separator': "warn",
      'storybook/no-redundant-story-name': "warn",
      'storybook/prefer-pascal-case': "off",
      'storybook/story-exports': "off",
      'storybook/use-storybook-expect': "off",
      'storybook/use-storybook-testing-library': "off",
      'storybook/no-uninstalled-addons': "error",
    },
  },
  {

    files: ['**/*.js', '**/*.cjs', '**/*.mjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
      },
    },
    linterOptions: {
      reportUnusedDisableDirectives: true,
    },
    
    rules: {
      "constructor-super": "error",
      "for-direction": "error",
      "getter-return": "error",
      "no-async-promise-executor": "error",
      "no-case-declarations": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": "error",
      "no-const-assign": "error",
      "no-constant-binary-expression": "error",
      "no-constant-condition": "error",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-delete-var": "error",
      "no-dupe-args": "error",
      "no-dupe-class-members": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": "error",
      "no-empty-character-class": "error",
      "no-empty-pattern": "error",
      "no-empty-static-block": "error",
      "no-ex-assign": "error",
      "no-extra-boolean-cast": "error",
      "no-fallthrough": "error",
      "no-func-assign": "error",
      "no-global-assign": "error",
      "no-import-assign": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-loss-of-precision": "error",
      "no-misleading-character-class": "error",
      "no-new-native-nonconstructor": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-obj-calls": "error",
      "no-octal": "error",
      "no-prototype-builtins": "error",
      "no-redeclare": "error",
      "no-regex-spaces": "error",
      "no-self-assign": "error",
      "no-setter-return": "error",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-this-before-super": "error",
      "no-undef": "off", //should be error
      "no-unexpected-multiline": "error",
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-labels": "error",
      "no-unused-private-class-members": "error",
      "no-unused-vars": "off", //should be error
      "no-useless-backreference": "error",
      "no-useless-catch": "error",
      "no-useless-escape": "error",
      "no-with": "error",
      "require-yield": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      'stylisticPlugin/indent': ['warn', 2],
      'one-var': 0,
      'no-tabs': 0,
      'no-path-concat': 0,
      'spaced-comment': 0,
      'space-before-blocks': 0,
      'space-before-function-paren': 0,
      'comma-dangle': [1, 'always-multiline'],
      'eol-last': 1,
      'no-mixed-spaces-and-tabs': 0,
      'no-multi-spaces': [
        2,
        {
          exceptions: {
            Property: true,
            VariableDeclarator: true,
            ImportDeclaration: true,
            ObjectExpression: true,
          },
        },
      ],
      'no-warning-comments': 1,
      //JSDocs
      'jsdoc/check-access': 'warn',
      'jsdoc/check-alignment': 'warn',
      'jsdoc/check-examples': 'off',
      'jsdoc/check-indentation': 'off',
      'jsdoc/check-line-alignment': 'off',
      'jsdoc/check-param-names': 'warn',
      'jsdoc/check-property-names': 'warn',
      'jsdoc/check-syntax': 'off',
      'jsdoc/check-tag-names': 'warn',
      'jsdoc/check-template-names': 'off',
      'jsdoc/check-types': 'warn',
      'jsdoc/check-values': 'warn',
      'jsdoc/convert-to-jsdoc-comments': 'off',
      'jsdoc/empty-tags': 'warn',
      'jsdoc/implements-on-classes': 'warn',
      'jsdoc/imports-as-dependencies': 'off',
      'jsdoc/informative-docs': 'off',
      'jsdoc/lines-before-block': 'off',
      'jsdoc/match-description': 'off',
      'jsdoc/match-name': 'off',
      'jsdoc/multiline-blocks': 'warn',
      'jsdoc/no-bad-blocks': 'off',
      'jsdoc/no-blank-block-descriptions': 'off',
      'jsdoc/no-blank-blocks': 'off',
      'jsdoc/no-defaults': 'warn',
      'jsdoc/no-missing-syntax': 'off',
      'jsdoc/no-multi-asterisks': 'warn',
      'jsdoc/no-restricted-syntax': 'off',
      'jsdoc/no-types': 'off',
      'jsdoc/no-undefined-types': 'off', //should be error
      'jsdoc/require-asterisk-prefix': 'off',
      'jsdoc/require-description': 'off',
      'jsdoc/require-description-complete-sentence': 'off',
      'jsdoc/require-example': 'off',
      'jsdoc/require-file-overview': 'off',
      'jsdoc/require-hyphen-before-param-description': 'off',
      'jsdoc/require-jsdoc': 'warn',
      'jsdoc/require-param': 'warn',
      'jsdoc/require-param-description': 'off', //should be error
      'jsdoc/require-param-name': 'warn',
      'jsdoc/require-param-type': 'off', //should be error
      'jsdoc/require-property': 'warn',
      'jsdoc/require-property-description': 'warn',
      'jsdoc/require-property-name': 'warn',
      'jsdoc/require-property-type': 'warn',
      'jsdoc/require-returns': 'off', //should be error
      'jsdoc/require-returns-check': 'warn',
      'jsdoc/require-returns-description': 'warn',
      'jsdoc/require-returns-type': 'warn',
      'jsdoc/require-template': 'off',
      'jsdoc/require-throws': 'off',
      'jsdoc/require-yields': 'warn',
      'jsdoc/require-yields-check': 'warn',
      'jsdoc/sort-tags': 'off',
      'jsdoc/tag-lines': 'warn',
      'jsdoc/text-escaping': 'off',
      'jsdoc/valid-types': 'warn',
    },
  },
  // lint JSON files
  {
    files: ["**/*.json"],
    ignores: ["**/package-lock.json"],
    language: "json/json",
    rules: {
      "json/no-duplicate-keys": "error",
      "json/no-empty-keys": "error",
      "json/no-unsafe-values": "error",
      "json/no-unnormalized-keys": "error",
      "json/sort-keys": "off",
      "json/top-level-interop": "error",
    },
    // ...json.configs.recommended,
  },
  {
    files: ['eslint.config.{js,cjs}'],
    languageOptions: {
      sourceType: 'script',
      ecmaVersion: 'latest',
      globals: {
        require: 'readonly',
        module: 'readonly',
        __dirname: 'readonly',
      },
    },
  },
];
