# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
  pull_request:

jobs:
  chromatic:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    env:
      HAVE_CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN != '' }}
      IS_CHROMATIC_DISABLED: ${{ vars.CHROMATIC_DISABLED == 'True' }}
    
    steps:
      - name: Publish to Chromatic
        if: ${{ env.HAVE_CHROMATIC_PROJECT_TOKEN == 'true' && env.IS_CHROMATIC_DISABLED == 'false'}}
        uses: chromaui/action@latest
        # Options required to the GitHub Chromatic Action
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          token: ${{ secrets.GH_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # 👇 tell Chromatic to rebuild the entire project when a file matching the pattern is changed https://www.chromatic.com/docs/github-actions/#enable-turbosnap
          #externals: |
          #  *.sass
          #  public/**
          onlyChanged: true # 👈 Required option to enable TurboSnap
          storybookBuildDir: "storybook-static"
          fetch-depth: 0
          # 👇 Tells the checkout which commit hash to reference
          ref: ${{ github.event.pull_request.head.ref }}
        env:
          CHROMATIC_BRANCH: ${{ github.event.pull_request.head.ref || github.ref_name }}
          CHROMATIC_SHA: ${{ github.event.pull_request.head.sha || github.ref }}
          CHROMATIC_SLUG: ${{ github.repository }}
      - name: Publish to Chromatic - Is Skipped
        if: ${{ env.HAVE_CHROMATIC_PROJECT_TOKEN != 'true' }}
        run: |  
          echo "### Chromatic not configured" >> $GITHUB_STEP_SUMMARY
          echo "secrets.CHROMATIC_PROJECT_TOKEN not existing, chromatic did not publish" >> $GITHUB_STEP_SUMMARY
          echo "If this is a fork, please setup your own personal chromatic at" >> $GITHUB_STEP_SUMMARY
          echo "[chromatic setup](https://www.chromatic.com/setup)" >> $GITHUB_STEP_SUMMARY
